name: Docker

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker
      env:
        REPOSITORY: docker.pkg.github.com
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
         COMMIT_ID=$(echo $GITHUB_SHA | head -c 6)
         PKGID=$REPOSITORY/lnsp/pgsql-backup-s3/backup:$COMMIT_ID
         docker login -u $USERNAME -p $PASSWORD $REPOSITORY
         docker build -f Dockerfile -t $PKGID .
         docker push $PKGID
